### PR TITLE
Add externals to checkout a cime version to use within mizuRoute standalone

### PR DESCRIPTION
**Pull request by ekluzek**
Adding in manage_externals to mizuRoute so that a version of cime can be pulled in for use in mizuRoute standalone. This will allow mizuRoute to use PIO as well as mct/mpi-serial and other shared code in cime that might be useful. We could have an external checkout of pio and mct alone, but it seems useful to bring in the whole of cime as other bits of code might be useful.

At this point I have the manage_externals working, but it's NOT hooked up to the build. SO NOT READY TO MERGE YET.

### CODE REVIEW

**Comment by ekluzek** [comment]
OK, I think this is ready to go, as far as I can see.

**Comment by ekluzek** [comment]
@jedwards pointed out that we should look into the PIO2 autoconf build. I looked into that and formed the following opinion

> "I think the main advantage of the autoconf build is that it can find NetCDF for you as well as MPI. It also checks for PNETCDF and does some checking to see if you have a parallel NetCDF-4 library. The build of mizuRoute already has to know about NetCDF and MPI, so the main thing desired is to make sure you are using the same one. And I think doing the same for PNETCDF works sufficiently well. I think the CMAKE build might do some checking about NetCDF-4, but I'm not sure. But, I'm also thinking you aren't likely to use NetCDF-4 so it doesn't matter.
> 
> So I think the build as it is, makes sense for what you need in the standalone mizuRoute build. I don't see a reason to convert it to the autoconf build. What would actually be better, would be to extend your current build system with autoconf so that it finds NetCDF and MPI for you."

**Comment by nmizukami** [comment]
@ekluzek ,   should I use "squash and merge" or just "create a merge" (keep all your commits)?

**Comment by ekluzek** [comment]
Up to you -- it's a personal preference. Personally I don't mind having the extra history and information from more commits. Sometimes it can be useful to have. If you want to see this change as one set of changes though -- you'll want to use squash. Sometimes seeing a bunch of commits that someone else did, isn't as useful as your own commits. So that would recommend using squash.

**Pull request merged**
